/**
 * BackendFondos
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BackendFondosApplicationDTOsClienteDto { 
    saldoDisponible?: number | null;
    fondosActivos?: Array<string> | null;
    preferenciaNotificacion?: string | null;
    nombre?: string | null;
    clienteID?: string | null;
    email?: string | null;
}

