/**
 * BackendFondos
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BackendFondosApplicationDTOsClienteDto { 
    saldoDisponible?: number;
    fondosActivos?: Array<string>;
    preferenciaNotificacion?: string;
    nombre?: string;
}

